# Generated by Django 4.1.3 on 2023-02-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('james', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
